version: '3.1'

services:

  reverseproxy:
    image: robertaro/game-of-life-reverse-proxy:latest
    restart: always
    ports:
      - 80:80

  react:
    image: robertaro/game-of-life-react:latest
    restart: on-failure
    stdin_open: true

  game-runner:
    image: robertaro/game-of-life-runner:latest
    restart: on-failure
    stdin_open: true

  user-api:
    image: robertaro/game-of-life-user-api:latest
    restart: always
    expose:
      - 3001
      
  game-history-api:
    image: robertaro/game-of-life-game-history-api:latest
    restart: always
    expose:
      - 3003