version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: game_of_life
    expose:
      - 3306
    volumes:
      - ./mysqldata:/var/lib/mysql
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  react:
    image: robertaro/game-of-life-react
    restart: always
    ports:
      - 80:80

  game-runner:
    image: robertaro/game-of-life-game-runner
    restart: always
    expose:
      - 3004

  user-api:
    image: robertaro/game-of-life-user-api
    restart: always
    expose:
      - 3001

  active-games-api:
    image: robertaro/game-of-life-active-games-api
    restart: always
    expose:
      - 3002

  game-history-api:
    image: robertaro/game-of-life-game-history-api
    restart: always
    expose:
      - 3003