version: '3.1'

services:

  react:
    image: react
    restart: on-failure
    ports:
      - 3000:3000
    stdin_open: true

  game-runner:
    image: robertaro/game-of-life-game-runner:latest
    restart: on-failure
    stdin_open: true

  user-api:
    image: robertaro/game-of-life-user-api:latest
    restart: always
    expose:
      - 3001
  
  active-games-api:
    image: robertaro/game-of-life-active-games-api:latest
    restart: always
    ports:
      - 3002:3002
      
  game-history-api:
    image: robertaro/game-of-life-game-history-api:latest
    restart: always
    expose:
      - 3003